"""empty message

Revision ID: 196af41ff3be
Revises: d2f327f46e30
Create Date: 2026-06-20 19:19:49.892680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '196af41ff3be'
down_revision = 'd2f327f46e30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personajes_favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuarioID', sa.Integer(), nullable=False),
    sa.Column('personajeID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['personajeID'], ['personajes.id'], ),
    sa.ForeignKeyConstraint(['usuarioID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personajes_favoritos')
    # ### end Alembic commands ###
