"""empty message

Revision ID: d2f327f46e30
Revises: 0f95c9a790bd
Create Date: 2026-06-20 01:19:41.452953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2f327f46e30'
down_revision = '0f95c9a790bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('PlanetaID', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'planetas', ['PlanetaID'], ['id'])

    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.alter_column('clima',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.alter_column('clima',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('PlanetaID')

    # ### end Alembic commands ###
